from setuptools import find_packages, setup

setup(
    name='netbox-scion',
    version='0.1.0',
    description='NetBox plugin for managing SCION Links Assignment',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    author='SCION Plugin Team',
    author_email='contact@example.com',
    install_requires=[],
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    keywords='netbox netbox-plugin scion',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: Apache Software License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Framework :: Django',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
    ],
)
